### ISSUE TITLE
Who wants this repo

### ISSUE THREAD

**Issue by ehren123** [io0/WinMuseEEG#2]
Hey All,

Probably gonna drop this repo since I don't plan on having any future use of it. Does anyone else want it? I will give it to them.

Thanks...

**Comment by crocodoyle** [comment]
I think @io0 should take it over since she's got the most code committed other than you

**Comment by io0** [comment]
Sure, I'll see if there's anything I can do with it. Thanks!

**Comment by ehren123** [comment]
Transfer in progress.
